# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Cname', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('Credit', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.CharField(max_length=9)),
                ('Cname', models.CharField(max_length=30)),
                ('Grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sno', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=20, unique=True)),
                ('Sdept', models.CharField(max_length=20)),
                ('Spwd', models.CharField(max_length=20)),
            ],
        ),
    ]
